version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts
    environment:
      # Variables used in build steps
      # from https://developer.salesforce.com/tools/sfdxcli
      - DX_CLI_URL: https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
      - TESTLEVEL: RunLocalTests
      - DEPLOYDIR: src
    steps:
      - checkout
      - run:
          name: "Create SFDX Folder"
          command: |
            # Create sfdx directory
            mkdir ~/sfdx
      - run:
          name: Download CLI
          command: |
            # Download cli
            # By default, the script installs the current version of Salesforce CLI. To install the release candidate, set the DX_CLI_URL_CUSTOM local variable to the appropriate URL
            wget -qO- ${DX_CLI_URL_CUSTOM-$DX_CLI_URL} | tar xJ -C ~/sfdx --strip-components 1
      - run:
          name: Install CLI
          command: |
            # Install the cli
            export PATH=~/sfdx/bin:$PATH
            echo "export PATH=~/sfdx/bin:$PATH" >> $BASH_ENV
            sfdx
      - run:
          name: Login to Org
          command: . build/login_to_sandbox.sh
      - run:
          name: Run Apex Tests
          command: . build/run_apex_tests.sh
      - store_test_results:
          path: test-results
workflows:
  version: 2
  validate:
    jobs:
      - run-tests
      # - code-review:
      #     requires:
      #       - run-tests
      # - deploy-code:
      #     requires:
      #       - code-review
