version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:16 # Using Node.js Docker image (adjust version if needed)
    working_directory: ~/repo

jobs:
  install_dependencies:
    executor: node-executor
    steps:
      - checkout # Checkout the project code
      - run:
          name: Install Node.js dependencies
          command: |
            npm install

  sfdx_auth:
    docker:
      - image: cimg/python:3.9 # Using Python for Salesforce CLI
    steps:
      - checkout # Checkout the project code
      - run:
          name: Install Salesforce CLI via npm
          command: |
            # Install Salesforce CLI globally using npm
            npm install --global sfdx-cli

      - run:
          name: Authenticate to Salesforce
          command: |
            # Authenticate to Salesforce using the SF_AUTH_URL environment variable
            echo $SF_AUTH_URL | sfdx auth:sfdxurl:store -f - -a DevOrg

      - run:
          name: Check Salesforce CLI version
          command: |
            # Verify that Salesforce CLI is installed correctly
            sfdx --version

      - run:
          name: Update Salesforce CLI
          command: |
            # Update Salesforce CLI if needed
            sfdx update

  test:
    executor: node-executor
    steps:
      - checkout # Checkout the project code
      - run:
          name: Run Jest tests
          command: |
            npm test

workflows:
  version: 2
  setup_and_test:
    jobs:
      - install_dependencies
      - sfdx_auth
      - test:
          requires:
            - install_dependencies
            - sfdx_auth
