version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:16 # Using Node.js Docker image (adjust version if needed)
    working_directory: ~/repo

jobs:
  install_dependencies:
    executor: node-executor
    steps:
      - checkout # Checkout the project code
      - run:
          name: Install Node.js dependencies
          command: |
            npm install

  sfdx_auth:
    docker:
      - image: cimg/python:3.9 # Using Python for Salesforce CLI
    steps:
      - checkout # Checkout the project code
      - run:
          name: Install Salesforce CLI
          command: |
            curl https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-x64.tar.xz -o sfdx-linux-x64.tar.xz
            if [ ! -f sfdx-linux-x64.tar.xz ]; then
              echo "Download failed or file not found!"
              exit 1
            fi
            file sfdx-linux-x64.tar.xz
            tar xvf sfdx-linux-x64.tar.xz
            ./sfdx/install
            ./sfdx/bin/sfdx update

      - run:
          name: Authenticate to Salesforce
          command: |
            echo $SF_AUTH_URL | sfdx auth:sfdxurl:store -f - -a DevOrg

  test:
    executor: node-executor
    steps:
      - checkout # Checkout the project code
      - run:
          name: Run Jest tests
          command: |
            npm test

workflows:
  version: 2
  setup_and_test:
    jobs:
      - install_dependencies
      - sfdx_auth
      - test:
          requires:
            - install_dependencies
            - sfdx_auth
