version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts
    environment:
      # Variables used in build steps
      # from https://developer.salesforce.com/tools/sfdxcli
      - DX_CLI_URL: https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
      - TESTLEVEL: RunLocalTests
      - DEPLOYDIR: src
    steps:
      - checkout
      - run:
          name: "Create SFDX Folder"
          command: |
            # Create sfdx directory
            mkdir ~/sfdx
      - run:
          name: Download CLI
          command: |
            # Download cli
            # By default, the script installs the current version of Salesforce CLI. To install the release candidate, set the DX_CLI_URL_CUSTOM local variable to the appropriate URL
            wget -qO- ${DX_CLI_URL_CUSTOM-$DX_CLI_URL} | tar xJ -C ~/sfdx --strip-components 1
      - run:
          name: Install CLI
          command: |
            # Install the cli
            export PATH=~/sfdx/bin:$PATH
            echo "export PATH=~/sfdx/bin:$PATH" >> $BASH_ENV
            sfdx
      - run:
          name: Authorize Target Deployment Org
          command: |
            #Authorize target org
            sfdx auth:jwt:grant --instance-url $ENDPOINT --client-id $CONSUMER_KEY --jwt-key-file assets/server.key --username $USER_NAME --alias UAT
